#!/usr/bin/env python3
"""Refresh the self-hosted webfonts in assets/fonts + assets/css/fonts.css.

Asks Google Fonts for the stylesheet a modern browser would get (woff2),
downloads the Latin and Latin Extended files, and rewrites fonts.css to
point at the local copies. Run it after adding a weight to FAMILIES.

    python3 tools/fonts/fetch_fonts.py
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SUBSETS = ('latin', 'latin-ext')
FAMILIES = 'family=Sora:wght@400;600;700&family=Source+Sans+3:wght@400;600'
UA = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')

HEADER = """/* Deccan Birders — self-hosted webfonts.
 *
 * Served from this domain instead of fonts.googleapis.com: one less
 * third-party connection on every page, and no request to Google from a
 * visitor's browser. Latin and Latin Extended only (the site's alphabet).
 * Generated by tools/fonts/fetch_fonts.py — edit that, not this file.
 * Sora and Source Sans 3 are both SIL Open Font License 1.1.
 */

"""


def fetch(url, out=None):
    cmd = ['curl', '-sS', '--fail', '-A', UA, url]
    if out:
        cmd += ['-o', str(out)]
    res = subprocess.run(cmd, capture_output=not out, text=not out)
    if res.returncode:
        sys.exit(f'failed to fetch {url}')
    return res.stdout if not out else None


def main():
    fonts_dir = ROOT / 'assets' / 'fonts'
    fonts_dir.mkdir(parents=True, exist_ok=True)
    css = fetch(f'https://fonts.googleapis.com/css2?{FAMILIES}&display=swap')

    blocks = re.findall(r'/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)
    out, kept = [], set()
    for subset, block in blocks:
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r'font-weight:\s*(\d+)', block).group(1)
        url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
        name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"
        fetch(url, fonts_dir / name)
        kept.add(name)
        out.append(f"/* {family} {weight} — {subset} */\n" + block.replace(url, f'../fonts/{name}').strip())

    (ROOT / 'assets' / 'css' / 'fonts.css').write_text(HEADER + '\n\n'.join(out) + '\n')

    stale = [f for f in fonts_dir.glob('*.woff2') if f.name not in kept]
    for f in stale:
        f.unlink()
    print(f'{len(kept)} font files, {len(stale)} stale removed')


if __name__ == '__main__':
    main()
